# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

os: linux
arch:
  - arm64
  - ppc64le
  - s390x
language: R
sudo: false
cache: packages
after_success:
    - Rscript -e 'covr::codecov()'
