ignore:
  - "R/archive_funcs.R"

comment: false

coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
    patch:
      default:
        target: auto
        threshold: 1%

codecov:
  token: 77af5300-721c-4494-bcd7-55091df4ae25
